notification:
  bark_key: ''
  serverchan_key: ''

# === 猫眼: 薛之谦万兽之王广州站 ===
maoyan:
  device_id: '3KQYD25227201783'
  viewer_name: '李岸洲'
  sale_time: '2026-02-26 17:17:00'
  concert_name: 薛之谦万兽之王巡回演唱会-广州站
  price: 1317

# === 大麦: 薛之谦万兽之王广州站（2月28日测） ===
damai:
  device_id: ''
  viewer_name: ''
  sale_time: '2026-02-28 17:17:00'
  concert_name: 薛之谦万兽之王巡回演唱会-广州站
  price: 317
  buy_btn: [1600, 2650]
  confirm_btn: [920, 2500]

# === 票星球: 颜人中福州站 ===
piaoxingqiu:
  access_token: eyJ0eXAiOiJKV1QiLCJjdHkiOiJKV1QiLCJ6aXAiOiJERUYiLCJhbGciOiJSUzUxMiJ9.eNp8kMFqwzAMht9F5xxk2ZbjHjM6NtgYlJWx03AdG8LWOCQurCt999lk9DgdpU__J3SB5bzcpT7AhrCB0xLmxzEm2FzgMPysA7h_ePp4hgaW06G7NZnYuBZD6Em0WpFpOQplVeHK5r4G9RWzNkrtkbhlJEQUHqNVFTtmf8O0dRqDdOgjkVbSOn9gZ8WatktfVdnt37c7uDYwuTkPeUhjFRQkp88w_umcQM29Uz1xrDpVytg152UKs8vp38tkQf0cXA6vw7FYhTEkGCVrkm35wezL7tu2q9rzVIEGwve0gqTYsL7-AgAA__8.YOFuLWL_RYvKzK9qXUQe9mRjxTgCs2j0y67HWOKoezRNd3YfsMEd-HtF84RhKSEp6r5Z_7_ynRpIsDbUCGuC8VwYVRJR5X8kuqAoXZQPKHjzGNvPXyX6IJa47yEKr8FrPqeobcy-oW4i5ogQWND_hTOcfa3Jv1ImQxLViu7z5i0
  concurrent_requests: 10
  phone: '15168369785'
  refresh_token: eyJ0eXAiOiJKV1QiLCJjdHkiOiJKV1QiLCJ6aXAiOiJERUYiLCJhbGciOiJSUzUxMiJ9.eNp8kE1rwzAMhv-LzjnI8lfcY0bLBhuDsjJ2Go4_IGyNQ-LCutL_PnsZPU5H6dH7CF1gOS93yQfYEDZwWsL8MMYEmwv0w_c6gN394_sTNLCc-u7WVKS0bTEET6yVgnSrIhNGFK5sHmqQr5gxkUuHpFqFhIjMYTSiYsfsbpg0VmLgFl0kkoIb63plDVvT9umzKrvD23YP1wYmO-chD2msgoLk9BHGP51lKJW3wpOKVSdKabPmPE9htjn9exkvqJuDzeFlOBYr05qYQq4k8bb8YHZl93XbVe15qn9rIHxNv6DmQhTw-gMAAP__.Jz3TaD42lF5hf9XSxjCCA6OBZdK85pyZ3FJyAiYizjrvPuysFWqBy9uTCWEPiOmUt35DT1iqiJ_bUyLhRsM-VRTdzWWxRrRSm3hYlOkUXIDuhNVheRiRA0rO_lTrGtPjsvd6dpTQvQVgPphLiTH35KsGuUCta7NEW8ZEB7z4uIw
  sale_time: '2026-02-27 12:00:00'
  concert_name: 颜人中福州站
  price: 380
  show_id: '6971a7be499f4c0001cdf188'
  session_id: '6971a86ca287b200010c6410'
  seat_plan_id: '6971a93d22d4110001ed00ab'
  # === 周杰伦杭州站（正式用，测完切回） ===
  # show_id: '698b06430fc9eb00019b46e4'
  # session_id: '698b06610fc9eb00019b4742'
  # seat_plan_id: '698c19a92dfcfa0001f80fdb'
